export enum SectionsEnum {
  'ability-scores' = 'Ability Scores',
  'alignments' = 'Alignments',
  'backgrounds' = 'Backgrounds',
  'classes' = 'Classes',
  'conditions' = 'Conditions',
  'damage-types' = 'Damage Types',
  'equipment' = 'Equipment',
  'equipment-categories' = 'Equipment Categories',
  'feats' = 'Feats',
  'features' = 'Features',
  'languages' = 'Languages',
  'magic-items' = 'Magic Items',
  'magic-schools' = 'Magic Schools',
  'monsters' = 'Monsters',
  'proficiencies' = 'Proficiencies',
  'races' = 'Races',
  'rule-sections' = 'Rule Sections',
  'rules' = 'Rules',
  'skills' = 'Skills',
  'spells' = 'Spells',
  'subclasses' = 'Subclasses',
  'subraces' = 'Subraces',
  'traits' = 'Traits',
  'weapon-properties' = 'Weapon Properties',
}
